### PR TITLE
Small comma and batch_size placement

### PR DESCRIPTION
**Pull request by nstrayer**
When I was working my way through this (awesome) post I noticed two things. First, when I went to copy and paste the prereq packages I got a confusing error caused by a missing comma. 

Second in the code that gets run the variable `batch_size` is called before it is defined. I added it here where it is needed but I'm not sure it's the best way to do it as it's a tiny bit out of the blue. Let me know if you have another preference (e.g. functionalizing the dataset generation to take `batch_size` as an argument?).

Small note: I simply modified the html file by hand because of how long it takes to run the code. Hopefully that's not a no-no.

### CODE REVIEW

**Comment by skeydan** [comment]
Hi Nick,

thanks for so much attention reading the attention post :-) !!

Right about the comma, sorry about the confusion, that happened because later I put reticulate first...

About placement of ```batch_size```, I was not expecting people to copy-paste this chunk-by-chunk and therefore I linked to the complete example (https://github.com/rstudio/keras/blob/master/vignettes/examples/nmt_attention.R) where everything is in execution order.
(For example, there the ```evaluate``` and ```plot_attention``` functions are defined before the training loop.)
This (I was thinking) gave me the freedom to introduce things in a "logical order" (although you might say in case of ```batch_size```, logical is where we define the dataset, whereas I was putting it with the NN hyperparams).

But I should have written this right in the beginning - that will be the case in all upcoming posts that have complete, technical examples like this.

BTW it's no problem (and probably better)  to modify the .Rmd and then knit, this will be super fast as ```eval=FALSE```.

**Comment by jjallaire** [comment]
Okay, let's add the comma as is done in this PR and then let's also add a note indicating that readers that want to execute the code should do so from the linked script rather than by copy/paste from the post.

**Comment by skeydan** [comment]
created https://github.com/rstudio/tensorflow-blog/pull/5
thanks again Nick!
@jjallaire the new branches have a similar note before actual code snippets already...

**Comment by nstrayer** [comment]
Shoot, I should have read the article closer! I also noticed the `eval = FALSE` setting after this PR. I was too excited about the code to pay enough attention apparently. 

As a note: the code does execute properly in order with the change of just that batch size variable and then adding print calls to the batch/epoch score messages. I agree though that it takes long enough that the notebook format is probably not the best way to run the code.

**Comment by nstrayer** [comment]
@skeydan I saw you already created a PR w/ the proper fix of the commas. Let me know if I can do anything else! Sorry to have prematurely submitted the PR without realizing I could have knitted easily!

**Comment by skeydan** [comment]
No problem, and thanks again! 

>> Shoot, I should have read the article closer! I 

Not at all, my fault, I should have alerted readers to that right in the beginning! It'll be like that in the upcoming ones on eager execution... (4 to come, at least!)
I'm happy to hear you're excited about it - to me, it really makes some things easier than before!

**Pull request closed without merging**
